
services:
  
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:17rc1-alpine
    restart: always 
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  postgres_data:
